// reactjs-product-management-boilerplate/src/App.js
import './App.css';
import axios from 'axios';
import AddProduct from './Components/AddProduct';
import { useState, useEffect } from "react";
import ProductsData from './Components/ProductsData';
function App() {
  let url = 'http://localhost:3001/products';
  // Write Your Code Here

  
  return (
    <div className="App">
      {/* Write Your Code Here */}    
      <AddProduct/>  
      <ProductsData/>
    </div>
  );
}

export default App;

// angular-product-management-boilerplate/src/app/app.component.ts
import { Component } from '@angular/core';
import { ProductService } from './services/product.service';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  title = 'productapp';
  constructor(private service: ProductService) { }

  products: Array<any> = [];

  ngOnInit(): void {
    // Write Your Code Here
  }

  addProduct(product: any) {
    // Write Your Code Here
  }

  deleteProduct(id: any) {
    // Write Your Code Here
  }

}

<!-- Write Your Code Here -->
<app-addproduct></app-addproduct>
<app-productsdata></app-productsdata>
