// reactjs-product-management-boilerplate/src/Components/ProductsData.js
import React, { useEffect, useState }from 'react'
import Product from './Product';

export default function ProductsData(props) {
    const [products, setProducts]=useState([]);

    useEffect(()=>{
        fetch('http://localhost:3001/products')
        .then(res=>res.json())
        .then(data => {
            setProducts(data);
        });
     },[]);
     const DeleteContactCard=(id)=>{
        fetch(`http://localhost:3001/products/${id}`,{
            method: 'DELETE'
        })
          .then(res=>res.json())
          .then(data=>{
          });
        setProducts(products.filter(item => item.id !=id));
     }
    return (
        <div>
            <table className="table" >
                <thead>
                    <tr>
                        <th scope="col">#</th>
                        <th scope="col">ProductName</th>
                        <th scope="col">Brand</th>
                        <th scope="col">Quantity</th>
                        <th scope="col">Price</th>
                        <th scope="col">Actions</th>
                    </tr>
                </thead>
                <tbody>
                    {/* Write Your Code Here */}
                </tbody>
            </table>
            {
              products.map(item =><Product deleteContact={DeleteContactCard} key={item.id} id={item.id} prodname={item.prodname} brand={item.brand} quility={item.quility} price={item.price}/>)
            }
        </div>
    )
}

// angular-product-management-boilerplate/src/app/productsdata/productsdata.component.ts
import { Component, EventEmitter, Input, OnInit, Output } from '@angular/core';
import { ProductService } from '../services/product.service';

@Component({
  selector: 'app-productsdata',
  templateUrl: './productsdata.component.html',
  styleUrls: ['./productsdata.component.css']
})
export class ProductsdataComponent {

  constructor(private service:ProductService) { }


  public products:Array<any>=[];


  // Write Your Code Here
  ngOnInit(){
    this.service.getProducts().subscribe((data:any)=>{
      // console.log(data);
      this.products=data;  
    });

  }

  deleteProduct(id: number){
    // Write Your Code Here
    console.log(id);  

      this.service.deleteProduct(id).subscribe((data:any)=>{
          this.service.getProducts().subscribe((prodData:any)=>{
            this.products=prodData;
          })
      })

  }

}

<div class="container mt-5">
    <table class="table">
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">ProductName</th>
                <th scope="col">Brand</th>
                <th scope="col">Quantity</th>
                <th scope="col">Price</th>
                <th scope="col">Actions</th>
            </tr>
        </thead>
        <tbody>
            <tr *ngFor="let product of products"> 
                <td>{{product.id}}</td>
                <td>{{product.name}}</td>
                <td>{{product.brand}}</td>
                <td>{{product.quantity}}</td>
                <td>{{product.price}}</td>
                <button type="submit" class="btn btn-danger" (click)="deleteProduct(product.id)">delete </button>

            </tr>
            <!-- Write Your Code Here -->
        </tbody>
    </table>
</div>
